
export default new Map([
["src/content/blog/a-comprehensive-guide-on-importing-customers.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fa-comprehensive-guide-on-importing-customers.mdx&astroContentModuleFlag=true")],
["src/content/blog/automatizacion-negocio-local-herramientas.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fautomatizacion-negocio-local-herramientas.mdx&astroContentModuleFlag=true")],
["src/content/blog/do-startup-valuations-matter-for-investment-returns.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fdo-startup-valuations-matter-for-investment-returns.mdx&astroContentModuleFlag=true")],
["src/content/blog/a-dynamic-back-office-is-the-new-business.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fa-dynamic-back-office-is-the-new-business.mdx&astroContentModuleFlag=true")],
["src/content/blog/marketing-digital-hispanos-florida.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fmarketing-digital-hispanos-florida.mdx&astroContentModuleFlag=true")],
["src/content/blog/redes-sociales-negocios-locales-guia-2025.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fredes-sociales-negocios-locales-guia-2025.mdx&astroContentModuleFlag=true")],
["src/content/blog/the-creator-economy-goes-global.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fthe-creator-economy-goes-global.mdx&astroContentModuleFlag=true")]]);
		